### PR TITLE
Enable Availability When One of N Fulfillment Centers has Product

### LINKED ISSUE #12: Inventory In Only the First Fulfillment Center is Accounted For
vc-storefront/VirtoCommerce.Storefront/Services/CatalogSearchServiceImpl.cs 

```
protected virtual async Task LoadProductInventoriesAsync(List<Product> products)
{
   var inventories = await _inventoryModuleApi.InventoryModule.GetProductsInventoriesAsync(products.Select(x => x.Id).ToList());

   foreach (var item in products)
   {
       item.Inventory = inventories.Where(x => x.ProductId == item.Id).Select(x => x.ToInventory()).FirstOrDefault();
    }
}
```

This function is assuming there are no other fulfillment centers to worry about.

## Options
- Add new property to return a collection of Inventory objects. (My Preference, continue to populate existing property for backwards compatibility.)
```
protected virtual async Task LoadProductInventoriesAsync(List<Product> products)
{
   var inventories = await _inventoryModuleApi.InventoryModule.GetProductsInventoriesAsync(products.Select(x => x.Id).ToList());

   foreach (var item in products)
   {
       item.Inventory = inventories.Where(x => x.ProductId == item.Id).Select(x => x.ToInventory()).FirstOrDefault();
       item.InventoryAll = inventories.Where(x => x.ProductId == item.Id).Select(x => x.ToInventory()).ToList();
    }
}

```
- Merge multiple returned inventory objects into one. (The object has a property for the fulfillment center so this would not be a great way)

### PR DESCRIPTION
**Pull request by montanehamilton**
Fixes #12 

It seems to work but let me know is this is a bit naïve. I did add a few test for the availability service.

### CODE REVIEW

**Comment by Woland2k** [comment]
There should be an option to select which fulfillment centers belong to that particular store (instead of just allowing selecting one).

**Comment by Woland2k** [comment]
@montanehamilton can you fill our contributor agreement so we can add you to a contributor team and accept your pull request?
 http://virtocommerce.com/contribute-agreement

**Comment by montanehamilton** [comment]
So yes I know about the setting for the store, which right now several settings on that blade are not able to be changed/saved.

Regardless I'm hoping Virto can support multiple fulfillment centers for a store, this fix at least allows them to exist, before it would not even potentially work if your fulfillment center was not the first one.

Happy to improve this based on direction...

**Comment by Woland2k** [comment]
Thanks Montane,

I added you to contributor team and thanks for the addition!

**Pull request merged**
